FAPEPI/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    path('index/', include('core.urls')),
    path('exame/', include('exame.urls')),
    path('coleta/', include('coleta.urls')),
    path('tipoExame/', include('tipoExame.urls')),
    path('paciente/', include('paciente.urls')),
]

coleta/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('novaFicha/', views.novaFicha, name='novaFicha'),
    path('novaColeta/', views.novaColeta, name='novaColeta'),
    path('salvarLaudo/', views.salvarLaudo, name='salvarLaudo'),
    path('coletarDados/', views.coletarDados, name='coletarDados'),
    path('get_dados_paciente/', views.get_dados_paciente, name='get_dados_paciente'),
    path('get_dados_tipo_exame/', views.get_dados_tipo_exame, name='get_dados_tipo_exame'),
    path('iniciarColeta/', views.iniciarColeta, name='iniciarColeta'),
    path('finalizarColeta/', views.finalizarColeta, name='finalizarColeta'),
    path('cancelarColeta/', views.cancelarColeta, name='cancelarColeta'),

]

core/urls.py
from django.urls import path
from core import views

urlpatterns = [
    path('', views.index, name='index'),
    path('red/', views.red, name='red'),
    path('blue/', views.blue, name='blue'),
    path('green/', views.green, name='green'),
    path('tone/', views.tone, name='tone'),

    path('selecionarDispositivo/', views.selecionarDispositivo, name='selecionarDispositivo'),
    path('devolverDispositivo/', views.devolverDispositivo, name='devolverDispositivo'),


]

coleta/models.py
from django.db import models
from tipoExame.models import TipoExame
from paciente.models import Paciente


class Coleta(models.Model):

    _QUEDA_RISCO_CHOICES = (
        ('ALTO', 'alto'),
        ('MEDIO', 'médio'),
        ('BAIXO', 'baixo'),
    )
    _PONTUACAO_CHOICES = (
        ('0', 0),
        ('1', 1),
        ('2', 2),
        ('3', 3),
        ('4', 4),
        ('6', 6),
        ('7', 7),
        ('8', 8),
        ('9', 9),
        ('10', 10),
    )

    numero_exec = models.PositiveSmallIntegerField(default=0)
    tipoExame = models.ForeignKey(TipoExame, on_delete=models.CASCADE, null=True)
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, null=True)
    observacao  = models.TextField('Observação', max_length=200, blank=True, null=True)



    riscoQueda = models.CharField('Risco de Queda', max_length=10, choices=_QUEDA_RISCO_CHOICES, default="None", blank=True, null=True)
    pontuacao = models.CharField('Pontuacao', max_length=10, choices=_PONTUACAO_CHOICES, default="None", blank=True, null=True)
    pontuacao_soma = models.CharField('Pontuacao Soma', max_length=10, blank=True, null=True)
    cronometro = models.CharField('Tempo', max_length=10, blank=True, null=True)
    deslocamento = models.CharField('Deslocamento cm', max_length=10, blank=True, null=True)


    visivel = models.BooleanField(default=False)
    amostras = models.TextField(blank=True, null=True)

    dataCriacao = models.DateTimeField('Criado em', auto_now_add=True)
    dataModificacao = models.DateTimeField('Atualizado em', auto_now_add=True)

paciente/forms.py
from django import forms
from paciente.models import Paciente

class EditarPacienteForm(forms.Form):
    nomeCompleto = forms.CharField(required=True)
    nomeCompletoCodeNome = forms.CharField(required=True)
    cpf = forms.CharField(required=False)
    sexo = forms.CharField(required=True)
    #nivelAtividade = forms.CharField(required=True)
    altura = forms.FloatField(required=True)
    peso = forms.FloatField(required=True)
    IMC = forms.FloatField(required=True)
    telefone = forms.CharField(required=False)
    dataNascimento = forms.DateField(required=False)
    observacao = forms.CharField(required=False)

    def is_valid_from_form(self):
        return super(EditarPacienteForm, self).is_valid()

    def is_valid(self, flag_edicao=False):

        valid = self.is_valid_from_form()
        if not valid:
            self.add_error(field=forms.ALL_FIELDS, error='Por favor, verifique os dados informados')
            return False

        elif not flag_edicao and Paciente.objects.filter(cpf=self.cleaned_data['cpf']).exists():
            self.add_error(field='cpf', error='CPF já cadastrado')
            return False

        elif not self.cleaned_data['sexo']:
            self.add_error(field='sexo', error='Selecione o sexo do paciente')
            return False

        return valid


class DeletarPacienteForm(forms.Form):

    nomeCompleto = forms.CharField(required=True)
    code_nomeCompleto = forms.CharField(required=True)

    def is_valid_from_form(self):
        return super(DeletarPacienteForm, self).is_valid()

    def is_valid(self, flag_edicao=False):
        valid = self.is_valid_from_form()
        if not valid:
            self.add_error(field=forms.ALL_FIELDS, error='Por favor, verifique os dados informados')
            return False
        return valid


class PacienteForm(forms.Form):

    nomeCompleto = forms.CharField(required=True)
    cpf = forms.CharField(required=False)
    sexo = forms.CharField(required=True)
    nivelAtividade = forms.CharField(required=True)
    altura = forms.FloatField(required=True)
    peso = forms.FloatField(required=True)
    IMC = forms.FloatField(required=True)
    telefone = forms.CharField(required=False)
    dataNascimento = forms.DateField(required=False)
    observacao = forms.CharField(required=False)

    def is_valid_from_form(self):
        return super(PacienteForm, self).is_valid()

    def is_valid(self, flag_edicao=False):

        valid = self.is_valid_from_form()

        if not valid:
            self.add_error(field=forms.ALL_FIELDS, error='Por favor, verifique os dados informados')
            return False
        # elif not flag_edicao and Paciente.objects.filter(nomeCompleto=self.cleaned_data['nomeCompleto'].replace(" ", "_").lower()):
        #     self.add_error(field='nomeCompleto', error='Nome já cadastrado')
        #     return False
        elif not flag_edicao and Paciente.objects.filter(visivel=True, cpf=self.cleaned_data['cpf']):
            self.add_error(field='nomeCompleto', error='CPF já cadastrado')
            return False

        elif not self.cleaned_data['nivelAtividade']:
            self.add_error(field='nivelAtividade', error='Selecione um Nível de atividade')
            return False

        elif not self.cleaned_data['sexo']:
            self.add_error(field='sexo', error='Selecione o sexo do paciente')
            return False

        return valid

coleta/views.py
from django.shortcuts import render, redirect
from django.views import View
from coleta.forms import ColetaForm, ColetaLaudoForm
from django.http import JsonResponse, HttpResponse
import json

from coleta.models import Coleta
from exame.models import Exame
from paciente.models import Paciente
from tipoExame.models import TipoExame
from avaliador.models import Avaliador

from paciente.PacienteBase import PacienteClass

import paho.mqtt.client as mqtt
import paho.mqtt.subscribe as subscribe
from datetime import timedelta
import time

pacienteClass = PacienteClass()

_IP_SERVER = "192.168.1.200"
_DIC_MQTT = {}

def on_start_coleta(client, userdata, msg):
    global _DIC_MQTT
    try:
        if int(msg.payload) >= int(("-80").encode()): # Sinal suficiente para inicar uma coleta
            _DIC_MQTT[str(msg.topic)]['flag_conexao'] = True

    except ValueError:
        if msg.payload == ("C2T").encode(): # Sinal de confirmação que foi iniciado a amostragem
            _DIC_MQTT[str(msg.topic)]['flag_start_coleta'] = True
        else:
            print("Não foi possível iniciar a coleta'")


def on_stop_coleta(client, userdata, msg):
    global _DIC_MQTT
    if msg.payload == ("C3T").encode():
        _DIC_MQTT[str(msg.topic)]['flag'] = False
    else:
        _DIC_MQTT[str(msg.topic)]['amostras'] += str(msg.payload.decode())

    print(str(msg.topic), " ", str(msg.payload.decode()))

def cancelarColeta(request):

    if request.is_ajax():
        return HttpResponse(json.dumps({'ok':True, 'msg': "Coleta Cancelada"}), content_type="application/json")

def iniciarColeta(request):
    global _DIC_MQTT;
    id_avaliador = str(request.user.avaliador.id)
    code_device = str(request.user.avaliador.dispositivo.codigo)
    topico_avaliador_MQTT = "device/"+id_avaliador+"/code"
    topico_dispositivo_MQTT = "device/"+code_device+"/code"
    _DIC_MQTT[topico_avaliador_MQTT] = {'time_out_conexao': 3, 'flag_conexao': False, 'time_out_start_coleta': 5,'flag_start_coleta': False}

    if request.is_ajax():
        client = mqtt.Client(client_id=str(request.user.avaliador.id), clean_session=True, userdata=None, protocol=mqtt.MQTTv31, transport="tcp")
        client.connect(_IP_SERVER, 1883, 60)
        client.on_message = on_start_coleta
        client.subscribe(topico_avaliador_MQTT)


        while _DIC_MQTT[topico_avaliador_MQTT]['time_out_conexao'] >= 0:
            _DIC_MQTT[topico_avaliador_MQTT]['time_out_conexao'] -= 1
            print(code_device, " Enviando comando C1 ...")
            client.publish(topico_dispositivo_MQTT, payload="C1"+id_avaliador, qos=2, retain=False)
            time.sleep(.1)
            for i in range(5):
                client.loop()
                time.sleep(.3)
            if _DIC_MQTT[topico_avaliador_MQTT]['flag_conexao']: break



        if _DIC_MQTT[topico_avaliador_MQTT]['flag_conexao']:
            print(code_device, " Comando C1 => OK")

            while _DIC_MQTT[topico_avaliador_MQTT]['time_out_start_coleta'] >= 0:
                _DIC_MQTT[topico_avaliador_MQTT]['time_out_start_coleta'] -= 1
                print(code_device, " Enviando comando C2 ...")
                client.publish(topico_dispositivo_MQTT, payload="C2"+id_avaliador, qos=2, retain=False)
                for i in range(5):
                    client.loop()
                    time.sleep(.5)
                if _DIC_MQTT[topico_avaliador_MQTT]['flag_start_coleta']: break



            if _DIC_MQTT[topico_avaliador_MQTT]['flag_start_coleta']:
                print(code_device, " Comando C2 => OK")
                client.disconnect()
                client.loop()
                del client
                return HttpResponse(json.dumps({'ok':True, 'msg': "Coleta Iniciada"}), content_type="application/json")
            else:
                client.disconnect()
                client.loop()
                del client
                return HttpResponse(json.dumps({'ok':False, 'msg': "Dispositivo Desconectado"}), content_type="application/json")

        else:
            client.publish(topico_dispositivo_MQTT, payload="SR", qos=2, retain=False)
            client.loop()
            client.disconnect()
            del client
            return HttpResponse(json.dumps({'ok':False, 'msg': "Dispositivo Desconectado, reiniciando..."}), content_type="application/json")

def finalizarColeta(request):

    global _DIC_MQTT;
    id_avaliador = str(request.user.avaliador.id)
    code_device = str(request.user.avaliador.dispositivo.codigo)
    topico_avaliador_MQTT = "device/"+id_avaliador+"/code"
    topico_dispositivo_MQTT = "device/"+code_device+"/code"

    if request.is_ajax():
        client = mqtt.Client(client_id=id_avaliador, clean_session=True, userdata=None, protocol=mqtt.MQTTv31, transport="tcp")
        client.loop()
        client.connect(_IP_SERVER, 1883, 60)
        client.loop()
        client.subscribe(topico_avaliador_MQTT)
        client.loop()
        client.publish(topico_dispositivo_MQTT, payload="C5", qos=2, retain=False)
        for i in range(5): client.loop()
        client.publish(topico_dispositivo_MQTT, payload="C3"+id_avaliador, qos=2, retain=False)
        for i in range(5): client.loop()
        _DIC_MQTT[topico_avaliador_MQTT] = {'amostras': "", 'flag': True}
        client.on_message = on_stop_coleta
        while _DIC_MQTT[topico_avaliador_MQTT]['flag']: client.loop()
        client.publish(topico_dispositivo_MQTT, payload="C4", qos=2, retain=False)
        for i in range(5): client.loop()
        client.disconnect()
        del client
        return HttpResponse(json.dumps({'ok':True, 'msg': "Coleta Finalizada com sucesso"}), content_type="application/json")

# Por JSON retorna os dados do paciente através do id paciente_search
def get_dados_paciente(request):
    dic_json = pacienteClass.get_dic_dados_paciente_search_json(request=request)
    return dic_json
####################################################################

# Por JSON retorna os dados do tipoExame através do id paciente_search
def get_dados_tipo_exame(request):
    tipoExame_search = request.GET.get('tipoExame_search', None)
    tipoExame = TipoExame.objects.get(nomeExame=tipoExame_search)
    nomeExame = tipoExame.nomeExame.replace("_"," ")
    pontuacao_soma = tipoExame.pontuacao_soma
    cronometro = tipoExame.cronometro
    deslocamento = tipoExame.deslocamento
    risco_queda = tipoExame.risco_queda
    coleta_dispositivo = tipoExame.coleta_dispositivo
    pontuacao = tipoExame.pontuacao
    observacao = tipoExame.observacao
    pontuacao_minima = tipoExame.pontuacao_minima
    pontuacao_maxima = tipoExame.pontuacao_maxima

    descricaoExame = tipoExame.descricao
    id = tipoExame.id
    data = {
        'nomeExame': nomeExame,
        'descricaoExame': descricaoExame,
        'id': id,
        'pontuacao_soma': pontuacao_soma,
        'observacao': observacao,
        'cronometro':  cronometro,
        'deslocamento': deslocamento,
        'risco_queda': risco_queda,
        'coleta_dispositivo': coleta_dispositivo,
        'pontuacao': pontuacao,
        'pontuacao_minima': pontuacao_minima,
        'pontuacao_maxima': pontuacao_maxima,
    }
    return JsonResponse(data)
######################################################################

def coletarDados(request):
    print("Coleando dados...")
    return render(request, "index.html")

def salvarLaudo(request):
    if request.is_ajax():
        form = ColetaLaudoForm(request.POST)
        if form.is_valid():
            global _DIC_MQTT
            topico_avaliador_MQTT = "device/"+str(request.user.avaliador.id)+"/code"
            dados = form.cleaned_data
            amostras = None

            if _DIC_MQTT.get(topico_avaliador_MQTT):
                amostras = _DIC_MQTT[topico_avaliador_MQTT]['amostras']
            else:
                amostras = "Não há amostras para esse tipo de exame"

            coleta_id = dados['coleta_id']
            observacao = dados['observacao']
            cronometro = dados['cronometro']
            pontuacao = dados['pontuacao']
            risco_queda = dados['risco_queda']
            deslocamento = dados['deslocamento']
            pontuacao_soma = dados['pontuacao_soma']


            coleta = Coleta.objects.filter(pk=coleta_id)

            coleta.update(observacao=observacao, cronometro=cronometro, deslocamento=deslocamento, pontuacao=pontuacao, pontuacao_soma=pontuacao_soma, riscoQueda=risco_queda, visivel=True, amostras=amostras)

            if topico_avaliador_MQTT in _DIC_MQTT: del _DIC_MQTT[topico_avaliador_MQTT]
            return HttpResponse(json.dumps({'ok':True, 'msg': "Sucesso"}), content_type="application/json")
        else:
            print("Erros: ", form.errors.as_data())
            return HttpResponse(json.dumps({'ok':True, 'msg': form.errors.as_data()}), content_type="application/json")

def novaColeta(request):
    if request.method == 'GET':
        context = {"pacientes": Paciente.objects.all().filter(visivel=True)}
        nome_exames = list(map( lambda t_e: t_e.nomeExame ,TipoExame.objects.all().filter(visivel=True)))
        context.update({"nome_exames": nome_exames})
        context.update({"exames_obj": TipoExame.objects.all().filter(visivel=True)})
        return render(request, 'coleta/novaColeta.html', context)
    elif request.method == 'POST':
        form = ColetaForm(request.POST)
        if request.is_ajax() and form.is_valid():
            dados = form.cleaned_data
            coleta = Coleta.objects.create(paciente_id=dados['paciente'][0].id,tipoExame_id=dados['tipoExame'][0].id)
            coleta.save()
            print("Nova Coleta post: ", coleta)

            exame = Exame.objects.filter(fk_paciente=dados['paciente'][0].id)[0]
            exame.fk_coleta.add(coleta)
            exame.save()

            return HttpResponse(json.dumps({'ok':True, 'msg': "Sucesso", 'id_coleta': coleta.id}), content_type="application/json")
        else:

coleta/templates/coleta/coletarDados.html
{% extends 'base_coleta.html' %}
{% block body %}

  <div class="navbar-fixed">
    <nav class=" blue-grey darken-4 z-depth-2">
        <div class="nav-wrapper">
          <a href="#"class="brand-logo center">
              <span id="header-large" class="text-logo"> Examinar </span>
          <a href="#" data-activates="menu-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
    </nav>
  </div>
  <ul class="side-nav" id="menu-mobile">
      <li><a href="{% url 'index' %}">Home</a></li>
      <li><a href="{% url 'novoExame' %}">Buscar Exame</a></li>
  </ul>
  <!--NavBar-->
  <form class="col s12 m12 l12"  method="POST" id="myForm">
    {% csrf_token %}
    <div class="grey lighten-5">
      </br>

      <div class="row">
        <div class="col s12 m12 l12">
          <div class="card grey lighten-4 z-depth-2">
            <div class="card-content white-text">

              <div class="row">
                <div class="input-field col s12 m12 l12">
                  <input id="id_nomeCompleto" name="nomeCompleto" value="QQWWEERRTTYU$$%*" type="text" disabled>
                  <label for="id_nomeCompleto">Nome completo</label>
                </div>
                <div class="input-field col s12 m12 l12">
                  <input id="id_cpf" name="cpf" value="QQWWEERRTTYU" type="text" disabled>
                  <label for="id_telefone">CPF</label>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>

    </div>
  </form>

{% endblock %}

coleta/templates/coleta/novaColeta.html
{% extends 'base_coleta.html' %}
{% block body %}

  <div class="navbar-fixed">
    <nav class=" blue-grey darken-4 z-depth-2">
        <div class="nav-wrapper">
          <a href="#"class="brand-logo center">
              <span id="header-large" class="text-logo"> Nova Coleta </span>
          <a href="#" data-activates="menu-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
        <div class="progress" >
          <div class="indeterminate" id="id_carregando_bar" hidden></div>
        </div>
    </nav>
  </div>
  <ul class="side-nav" id="menu-mobile">
      <li><a href="{% url 'index' %}">Home</a></li>
      <li><a href="{% url 'novoExame' %}">Buscar Exame</a></li>
      <li><a href="{% url 'novaColeta' %}">Nova Coleta</a></li>
  </ul>
  <!--NavBar-->

  <form class="col s12 m12 l12"  method="POST" id="id_form_coleta">
    {% csrf_token %}
    <!-- Div contendo os ids dos campos paciente e tipo exame -->
    <div class="row" hidden>
      <div class="input-field col s6 m6 l6">
        <input placeholder="" id="paciente" type="hidden" name="paciente"  value="{{context.nomeCompleto}}" readonly>
      </div>
      <div class="input-field col s6 m6 l6">
        <input placeholder="" id="tipoExame" type="hidden" name="tipoExame"  value="{{context.tipoExame}}" readonly >
      </div>
    </div>
    <!-- Div contendo os ids dos campos paciente e tipo exame -->
    <div class="grey lighten-5">
      <!-- Essa div contém todos os campos de busca para montar uma ficha de exames -->
      <div class="row" id="id_div_busca">
        <div class="col s12 m12 l12">
          <div class="card">
            <div class="card-content white-text">
              <!-- Campo de busca de Paciente -->
              {% if user.avaliador.dispositivo %}
                <div class="row">
                  <div class="input-field col s12 m12 l12">
                    <!-- <i class="material-icons prefix" style="color:#26a69a">accessibility</i> -->
                    <input placeholder="" id="search_paciente" name="search_paciente" value="{{context.nomeCompleto}}" type="text" class="search_paciente grey-text text-darken-4" autofocus required>
                    <label for="search_paciente">BUSCAR: Nome ou CPF</label>
                  </div>
                </div>
                <!-- Campo de busca de Paciente -->
                <!-- Campo de busca tipoExame -->
                <div class="row">
                  <div class="input-field col s12 m12 l12">
                    <!-- <i class="material-icons prefix" style="color:#26a69a">add_to_queue</i> -->
                    <input placeholder="" id="search_tipo_exame" name="search_tipo_exame" value="{{context.tipoExame}}" type="text" class="search_tipo_exame grey-text text-darken-4" required>
                    <label for="search_tipo_exame">Buscar Exame</label>
                  </div>
                </div>
                <!-- Campo de busca tipoExame -->
                <div class="section"/>

                <center>
                  <button id="id_button_gerar_ficha" class="waves-effect waves-light btn z-depth-3" type="submit" value="gerar_ficha" name="action">Gerar Ficha</button>
                </center>
              {% else %}
                <a href="{% url 'index' %}">
                  <h4 class="Blue-text center" >Selecione um dispositivo</h4>
                </a>
              {% endif %}

            </div>
          </div>
        </div>
      </div>
      <!-- Essa div contém todos os campos de busca para montar uma ficha de exames -->
    </div>
  </form>

  <!-- Essa div contem os campos do laudo do paciente -->
  <div class="row" id="id_div_ficha_exame" hidden>
    <form class="col s12 m12 l12" method="POST" id="id_form_laudo">
      {% csrf_token %}
      <input placeholder="" id="id_coleta_id" type="hidden" name="coleta_id">
      <div class="card">
        <div class="card-content white-text">
          <hr><h5 class="grey-text text-darken-1 center"> Ficha do Paciente</h5><hr></br>
          <div class="row">
            <div class="input-field col s12 m12 l12">
              <input placeholder="" id="id_nomeCompleto" name="nomeCompleto" type="text" disabled>
              <label for="id_nomeCompleto">Nome completo</label>
            </div>
            <div class="input-field col s12 m12 l12">
              <input placeholder="" id="id_cpf" name="cpf" type="text" disabled>
              <label for="id_telefone">CPF</label>
            </div>
            <div class="input-field col s12 m12 l12">
              <input placeholder="" id="id_dataNascimento" name="dataNascimento" type="text" disabled>
              <label for="id_dataNascimento">Data de Nascimento</label>
            </div>
            <div class="input-field col s12 m12 l12">
              <input placeholder="" id="id_tipoExame" name="tipoExame" type="text" disabled>
              <label for="id_tipoExame">Tipo Exame</label>
            </div>
            <div class="col s12 m12 l12 center">
              <span class="grey-text text-darken-1" id="id_descricao_tipo_exame"></span>
              <div class="section" id="id_div_field_cronometro" hidden>
                <span class="grey-text text-darken-1" id="id_cronometro" style="width:300px; height:100px; line-height:100px; font-size:75px; border:none;"></span>
              </div>
            </div>

            <div class="input-field col s12 m12 l12 grey-text text-darken-1 " hidden>
              <input id="id_cronometro_laudo" type="text" name="cronometro" value="00:00" readonly>
              <label for="id_cronometro_laudo" class="active" >Cronômetro</label>
            </div>

          </div>
          <div class="row" id="id_div_laudo_paciente" hidden>
            <hr><h5 class="grey-text text-darken-1 center"> Laudo do Paciente</h5><hr></br>
            <div class="input-field col s12 m12 l12" id="id_div_field_observacao" hidden>
              <textarea id="id_observacao" name="observacao" data-length="120" class="materialize-textarea grey-text text-darken-4"></textarea>
              <label for="id_observacao" class="active" >Observação</label>
            </div>
            <div class="input-field col s12 m12 l12 grey-text text-darken-4" id="id_div_field_deslocamento" hidden>
              <input placeholder="" id="id_deslocamento" name="deslocamento" type="number" value=""></textarea>
              <label for="id_deslocamento" class="active" >Deslocamento em cm</label>
            </div>

            <div class="input-field col s12 m12 l12 grey-text text-darken-4" id="id_div_field_pontuacao_soma" hidden>
              <input placeholder="" id="id_pontuacao_soma" name="pontuacao_soma" type="number" value=""></textarea>
              <label for="id_pontuacao_soma" class="active" >Pontuacao Soma</label>
            </div>


            <div class="input-field col s12 m12 l12" id="id_div_field_risco_queda" hidden>
              <h6 class="grey-text text-darken-1 center"> Risco de Queda</h6>
              </br>
              <select class="grey-text text-darken-4" id="id_field_risco_queda" name="risco_queda" required>
                  <option value="-----">Selecione um Risco</option>
                  <option value="BAIXO">BAIXO risco de queda</option>
                  <option value="MEDIO">MÉDIO risco de queda</option>
                  <option value="ALTO">ALTO risco de queda</option>
              </select>
            </div>

            <div class="input-field col s12 m12 l12" id="id_div_field_pontuacao" hidden>
              <h6 class="grey-text text-darken-1 center">Pontuação</h6>
              </br>
              <select class="grey-text text-darken-4" id="id_pontuacao" name="pontuacao" required>
                  <option value="-">-</option>
              </select>
            </div>
            <div class="col s12 m12 l12">
            </br></br>
              <center>
                <button id="id_button_salvar_laudo" class="waves-effect waves-light btn-large z-depth-3 " type="submit" value="salvar">Salvar Laudo</button>
              </center>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
  <!-- Essa div contem os campos do laudo do paciente -->

  <div id="id_div_dispositivo_rec" hidden>
    <form method="POST" id="id_form_mqtt_rec">
      {% csrf_token %}
      <center>
        <button id="id_button_iniciar_coleta" class="waves-effect waves-light btn z-depth-3" type="submit" value="iniciar_coleta">Iniciar Coleta</button>
      </center>
      </br></br></br>
   </form>
  </div>

  <div id="id_div_dispositivo_stop" hidden>
    <form method="POST" id="id_form_mqtt_stop">
      {% csrf_token %}
      <center>
        <button class="waves-effect waves-light btn yellow accent-4 grey-text text-darken-4 z-depth-3" type="submit" name="action">Parar Coleta</button>
      </center>
      </br></br></br>
   </form>
  </div>

  <div id="id_div_carregando_amostrar" hidden>
    <div class="section"/>
    <div class="section"/>
    <div class="section"/>
    <div class="section"/>
    <div class="section"/>
    <h5 class="center">Carregando Amostras...</h5>
    <div class="preloader-wrapper big active" style= "
     position: absolute;
     left: 50%;
     top: 50%;
     margin-left: -32px;
     margin-top: -32px;">
     <div class="spinner-layer spinner-blue">
        <div class="circle-clipper left">
          <div class="circle"></div>
        </div><div class="gap-patch">
          <div class="circle"></div>
        </div><div class="circle-clipper right">
          <div class="circle"></div>
        </div>
     </div>
     <div class="spinner-layer spinner-red">
        <div class="circle-clipper left">
          <div class="circle"></div>
        </div><div class="gap-patch">
          <div class="circle"></div>
        </div><div class="circle-clipper right">
          <div class="circle"></div>
        </div>
      </div>
     <div class="spinner-layer spinner-yellow">
        <div class="circle-clipper left">
          <div class="circle"></div>
        </div><div class="gap-patch">
          <div class="circle"></div>
        </div><div class="circle-clipper right">
          <div class="circle"></div>
        </div>
      </div>
     <div class="spinner-layer spinner-green">
        <div class="circle-clipper left">
          <div class="circle"></div>
        </div><div class="gap-patch">
          <div class="circle"></div>
        </div><div class="circle-clipper right">
          <div class="circle"></div>
        </div>
      </div>
    </div>
  </div>




{% endblock %}