FAPEPI/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    path('index/', include('core.urls')),
    path('exame/', include('exame.urls')),
    path('coleta/', include('coleta.urls')),
    path('tipoExame/', include('tipoExame.urls')),
    path('paciente/', include('paciente.urls')),
]

core/urls.py
from django.urls import path
from core import views

urlpatterns = [
    path('', views.index, name='index'),
    path('red/', views.red, name='red'),
    path('blue/', views.blue, name='blue'),
    path('green/', views.green, name='green'),
    path('tone/', views.tone, name='tone'),

    path('selecionarDispositivo/', views.selecionarDispositivo, name='selecionarDispositivo'),
    path('devolverDispositivo/', views.devolverDispositivo, name='devolverDispositivo'),


]

users/urls.py
from django.contrib.auth import views
from django.urls import include, path
from users.views import RegistrarUsuarioView

urlpatterns = [
    path('', views.login, {'template_name': 'users/login.html'}, name='login'),
    path('', views.logout, {'next_page':'users/login.html'}, name='logout'),
    path('cadastro/', RegistrarUsuarioView.as_view(), name="cadastro"),
]

users/models.py
from django.db import models

users/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrarForm(forms.Form):
    usuario = forms.CharField(required=True)
    senha = forms.CharField(required=True)
    senha_confirma = forms.CharField(required=True)
    email = forms.EmailField(required=True)



    def is_valid_from_form(self):
        return super(RegistrarForm, self).is_valid()

    def is_valid(self):

        valid = self.is_valid_from_form()
        if not valid:
            self.add_error(field=forms.ALL_FIELDS, error='Por favor, verifique os dados informados')
            return False
        elif User.objects.filter(username=self.cleaned_data['usuario']).exists():
            self.add_error(field='usuario', error='Usuário já cadastrado')
            return False
        elif User.objects.filter(email=self.cleaned_data['email']).exists():
            self.add_error(field='usuario', error='Email já cadastrado')
            return False
        elif self.cleaned_data['senha'] != self.cleaned_data['senha_confirma']:
            self.add_error(field='senha', error='Senhas não correspondem')
            return False
        return valid

users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.models import User

from django.contrib.auth import authenticate, login
from avaliador.models import Avaliador

from users.forms import RegistrarForm

class RegistrarUsuarioView(View):
    template_name = 'users/cadastro.html'

    def get(self, request):
        context = {}
        return render(request, self.template_name)

    def post(self, request):
        form = RegistrarForm(request.POST)
        if form.is_valid():
            dados = form.cleaned_data
            usuario = User.objects.create_user(username=dados['usuario'].replace(" ", "_").lower(),
                                               email=dados['email'],
                                               password=dados['senha'])
            usuario.save()
            avaliador = Avaliador.objects.create(user=usuario)
            avaliador.save()
            # user = authenticate(username=usuario.username, password=form.cleaned_data['password'])
            # login(request, user)
            return redirect('login')
        else:
            print("Usuario: ", form['usuario'].errors)
            print("Senha:", form['senha'].errors)
            print("Email:", form['email'].errors)
            return render(request, self.template_name, {'form': form})

users/templates/users/cadastro.html
{% extends 'base.html' %}
{% block body %}
<div class="navbar-fixed">
  <nav class="blue-grey darken-4 z-depth-2">
    <h5 class='center white-text' >Cadastre-se</h5>
  </nav>
</div>
<br>
<br class="col s12">
  <form class="col s12" method="post">
    {% csrf_token %}
    <div class="form-container">
      <div class="row">
        <div class="input-field col s12">
          <input placeholder="Ex: usuario123" id="id_usuario" name="usuario" type="text" class="validate" data-length="10" required >
          <label for="id_usuario">Usuário</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input placeholder="Ente com sua senha" id="id_senha" name="senha" type="password" class="validate" required {{ a_f }}>
          <label for="id_senha">Senha</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input placeholder="Insira novamente sua senha" id="id_senha_confirma" name="senha_confirma" type="password" class="validate" required>
          <label for="id_senha">Confirmar Senha</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input placeholder="Entre com email" id="id_email" name="email" type="email" class="validate" required>
          <label for="id_senha">Email</label>
        </div>
      </div>
    </div>
    <center>
      <button class="waves-effect waves-light btn z-depth-3 " type="submit" name="action">Cadastrar</button>
      <br>
    </center>
  </form>
</br>
</br>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}
{% block body %}
{% load static %}

<div class="navbar-fixed">
  <nav class="blue-grey lighten-5 z-depth-2">
    <!-- <h5 class='center black-text' >Login</h5> -->
    <span id="header-large" class="text-logo black-text"> Login </span>
  </nav>
</div>

 <div class="row">
  <div class="col s12 m12 l12">
    <div class="card">
      <div class="card-image">
        <img src="{% static 'img/002.png' %}">
      </div>
      <div class="card-content">
        <form class="" method="post">
          {% csrf_token %}
          <div class="form-container">
            {% for field in form %}
              <div class="row">
                <div class="input-field col s12">
                  {{ field.label_tag }}
                  {{ field }}
                  {{ field.errors }}
                </div>
              </div>
            {% endfor %}
          </div>
          <center>
            <button class="waves-effect waves-light btn z-depth-3 " type="submit" name="action">Entrar</button>
            <div class="section"/>
            <div class="section"/>
            <a href="{% url 'cadastro' %}">Cadastre-se</a>
          </center>
        </form>
      </div>
      <div class="card-action">
      </div>
    </div>
  </div>
</div>


{% endblock %}